### ISSUE TITLE
[PE-D][Tester C] UG "[ ]" meaning

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-2/tp#182]
There is no mention that "[ ]" explicity means the parameter is optional despite implication that it is.

![image.png](https://raw.githubusercontent.com/lm-44/ped/main/files/2e0b4e52-b8c1-46fe-9710-3028bf630f35.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: lm-44/ped#2

**Comment by ethan-goh** [comment]
add in UG that square brackets indicate optional fields
