### ISSUE TITLE
[PE-D][Tester E] Typo in page 8 of User Guide for "Use prefix c/." under "For filtering by Course"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-2/tp#190]
Description: In Page 8 of the User Guide, there is an extra fullstop for "Use prefix c/." which can be found under "For filtering by Course".

![Screenshot 2024-11-08 at 4.23.27 PM.png](https://raw.githubusercontent.com/suhayl13/ped/main/files/1ef88ad7-834e-4a14-8f37-03b15e78380a.png)

Steps to Reproduce:

Open the User Guide.
Go to page 8.
The typo can be found in bullet point "Use prefix c/."
Expected: "Use prefix c/"
Actual: "Use prefix c/."

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: suhayl13/ped#3

**Comment by jessica2828** [comment]
The full stop is found in bullet points for `n/ ` and `m/ `, we can remove to prevent confusion

**Comment by jessica2828** [comment]
all explanations remove full stops for bullet points
