### ISSUE TITLE
[PE-D][Tester E] Module command does not work despite meeting requirements stated in the User Guide and Error Message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-2/tp#194]
Description: The module command does not work despite meeting the criteria specified in the user guide and error message.
Steps to Reproduce:
1. Launch the app.
2. Ensure sample data with a person with Student ID 13131313 is present.
2. Enter `grade 13131313 m/Software Engineering g/A`

Expected Outcome: The person with ID 13131313 should have a module name Software Engineering.
Actual Outcome: The module command fails to execute and shows and error message.
![Screenshot 2024-11-08 at 4.38.08 PM.png](https://raw.githubusercontent.com/suhayl13/ped/main/files/6af5a37b-5cfb-4e19-9138-91e6aee42158.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: suhayl13/ped#4

**Comment by jessica2828** [comment]
#185

**Comment by jessica2828** [comment]
no spaces
