### ISSUE TITLE
[PE-D][Tester A] Invalid input for edit command is not specific

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-2/tp#197]
![Screenshot 2024-11-08 at 4.44.55 PM.png](https://raw.githubusercontent.com/gladwintan/ped/main/files/b7ac16e0-fbc9-447e-b3dd-c98ab7239ad0.png)

The command format is valid but the input for module prefix is invalid.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: gladwintan/ped#6

**Comment by btbrandon** [comment]
Error likely due to whitespace which this tester has created another issue for
