### ISSUE TITLE
[PE-D][Tester D] Wrong link in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-2/tp#206]
![Screenshot 2024-11-08 at 4.51.56 PM.png](https://raw.githubusercontent.com/rithiklenin/ped/main/files/807f10b7-bae6-404f-84eb-c200615b5fa5.png)
unable to click on it

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: rithiklenin/ped#10

**Comment by JYL27** [comment]
Fixed with #256
