### ISSUE TITLE
[PE-D][Tester B] Allow commands to use index instead of just ID

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-2/tp#209]
Since indexes are provided, it may be helpful to allow commands such as edit and delete using that? Typing the full student ID seems prone to mistakes. For instance, accidentally typing 12345677 instead of 12345678 could edit another student unintentionally. It would make the process more seamless, especially since contacts outside of displayed list cannot be modified anyway.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: kahsuann/ped#5

**Comment by juliantayyc** [comment]
+ planned enhancements 

close after including

**Comment by juliantayyc** [comment]
feature flaw
