### ISSUE TITLE
[PE-D][Tester D] Duplicate entries 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-2/tp#211]
![Screenshot 2024-11-08 at 4.58.12 PM.png](https://raw.githubusercontent.com/rithiklenin/ped/main/files/8b0de02f-bb33-47ae-9c63-7414ada337fc.png)

I am able to enter 2 exact same people just with a different studentID number. I think personally, the phone number should not be the same since each person has their own phone. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: rithiklenin/ped#11

**Comment by JYL27** [comment]
clarify that student ID is the unique identifier in UG

**Comment by btbrandon** [comment]
explain all the fields for the commands necessary
