### ISSUE TITLE
[PE-D][Tester E] The User Guide can have a glossary section for technical terms

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-2/tp#224]
Description: The User Guide contains terms in the product description like "CLI" and "GUI", which certain readers might not know what it means. Therefore, it will be good to include a glossary section for such technical terms so that the readers need to have to Google it, which may cause inconvenience to them.

Steps to Reproduce:
1. Launch the User Guide.
2. Go to the Table of Contents page

Expected Outcome: A section for glossary is present.
Actual Outcome:  A section for glossary is not present.
![Screenshot 2024-11-08 at 5.17.24 PM.png](https://raw.githubusercontent.com/suhayl13/ped/main/files/e831285e-6dc0-4f24-959e-33efe59d5f5e.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: suhayl13/ped#14

**Comment by jessica2828** [comment]
add footnote
