### ISSUE TITLE
[PE-D][Tester C] Delete Command output is inconsistent with screenshot in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-2/tp#242]
Although the specific command sent is different, the name of the parameters should be the same.
![image.png](https://raw.githubusercontent.com/lm-44/ped/main/files/98408f32-e100-4433-b013-fc5561906eee.png)

From UG
![image.png](https://raw.githubusercontent.com/lm-44/ped/main/files/f92cb2a0-a4af-4957-9fce-124fcb3b0bac.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: lm-44/ped#15

**Comment by ethan-goh** [comment]
update screenshot
